#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp32_template

EXTRA_COMPONENT_DIRS := H://LearnESP32/learn-esp32/esp32_template/main/source


include $(IDF_PATH)/make/project.mk

